Tashpa11/Pages/Courses/ManageCourses.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tashpa11.Mapping;
using Tashpa11.Model;

namespace Tashpa11.Pages.Courses
{
    public class ManageCoursesModel : PageModel
    {
        public string active_input { get; set; }
        public string submitNewButton { get; set; }
        public string delete_input { get; set; }
        public string deleteButton { get; set; }
        public string msg { get; set; }
        public string DisplayList { get; set; }
        public string insertMSG { get; set; }
        public string insert_button { get; set; }
        public string deleteMSG { get; set; }
        public Coursess List { get; set; } = new Coursess(); 
        public Course course { get; set; } = new Course(); 


        public void OnGet()
        {
            active_input = "display:none";
            submitNewButton = "display:none";
            DisplayList = "display:block";
            delete_input = "display:none";
            deleteButton = "display:none";                       
            CoursesDB db = new CoursesDB();
            List = db.SelectAll();
        }
        public void OnPostRenderCourses()
        {
            active_input = "display:none";
            submitNewButton = "display:none";
            DisplayList = "display:block";
            delete_input = "display:none";
            deleteButton = "display:none";
            CoursesDB db = new CoursesDB();
            List = db.SelectAll();
        }

        public void OnPostShowAddCourses()
        {
            DisplayList = "display:none";
            active_input = "display:block";
            insert_button = "display:block";
            delete_input = "display:none";
            deleteButton = "display:none";
        }
        public void OnPostShowDeleteCourse()
        {
            DisplayList = "display:none";
            active_input = "display:none";
            insert_button = "display:none";
            delete_input = "display:block";
            deleteButton = "display:block";
        }
        public void OnPostInsertCourse(string newCourseName, string newCourseNumber, string newCourseTeacher)
        {
            Course newCourse = new Course();
            CoursesDB db = new CoursesDB();
            newCourse.CourseName = newCourseName;
            newCourse.CourseNumber = newCourseNumber;
            newCourse.Name = newCourseTeacher;

            int records = db.Insert(newCourse);
            delete_input = "display:none";
            deleteButton = "display:none";
            if (records == 1)
            {
                insert_button = "disply:none";
                insertMSG = "Course Added Successfuly";
            }
            else { insertMSG = "Could Not Add Course !!!"; };
        }
    }
}

Tashpa11/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tashpa11.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Tashpa11/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tashpa11.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Tashpa11/Pages/Index1.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tashpa11.Pages
{
    public class Index1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Tashpa11/Pages/Login/Exit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tashpa11.Model;

namespace Tashpa11.Pages.Login
{
    public class ExitModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.SetString("Admin", "");
            HttpContext.Session.SetString("Username", "");
            HttpContext.Session.SetString("FirstName", "");

            return RedirectToPage("/Index");

        }
    }
}

Tashpa11/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tashpa11.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Tashpa11/Pages/Students/MangeMyCourses.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using Tashpa11.Model;
using Microsoft.AspNetCore.Http;
using Tashpa11.Mapping;


namespace Tashpa11.Pages.Students
{
    public class MangeMyCoursesModel : PageModel
    {
        public string active_input { get; set; }
        public string submitNewButton { get; set;}
        public string delete_input { get; set; }
        public string deleteButton { get; set; }
        public string msg { get; set; }
        public string List { get; set; }
        public string  DisplayList { get; set; }
        public string insertMSG { get; set; }

        public void OnGet()
        {
            active_input = "display:none";
            submitNewButton ="display:none";
            //List.Style.Add("display", "block");
            delete_input = "display:none";
            deleteButton = "display:none";
            //if (String.IsNullOrEmpty(HttpContext.Session.GetString("Username").ToString())) 
            msg = HttpContext.Session.GetString("Username").ToString();
            string studentName = HttpContext.Session.GetString("Username").ToString();
            IndividualStudentDB db = new IndividualStudentDB(studentName);
            List = db.RenderAllCourses();
        }

        public  void OnPostShowAddCourses()
        {
            DisplayList="display:none";
            active_input="display:block";
            submitNewButton="display:block";
            delete_input="display:none";
            deleteButton="display:none";
        }
        public void OnPostShowDeleteCourse()
        {
            DisplayList = "display:none";
            active_input = "display:none";
            submitNewButton = "display:none";
            delete_input = "display:block";
            deleteButton = "display:block";
        }
        public void OnPostInsertCourse(string newCourseName, string newCourseNumber, string newCourseTeacher)
        {
            Course newCourse = new Course();
            CoursesDB db = new CoursesDB();
            newCourse.CourseName = newCourseName;
            newCourse.CourseNumber = newCourseNumber;
            newCourse.Name = newCourseTeacher;

            int records = db.Insert(newCourse);
            if (records == 1) { insertMSG = "Course Added Successfuly"; }
            else { insertMSG = "Could Not Add Course !!!"; };
        }
    }
}

Tashpa11/Pages/Courses/ManageCourses.cshtml
@page
@model Tashpa11.Pages.Courses.ManageCoursesModel
@using Tashpa11.Model
@{
}

<div class="container my-5">
    <div class="d-flex justify-content-between gap-3">
        <form method="get" asp-page-handler="RenderCourses">
            <button type="submit" value="Show All Courses" class="btn btn-primary">Show All Courses</button>
        </form>
        <form method="post" asp-page-handler="ShowAddCourses">
            <button type="submit" value="Add Course" class="btn btn-primary">Add Course</button>
        </form>
        <form method="post" asp-page-handler="ShowDeleteCourse">
            <button type="submit" value="Delete Course" class="btn btn-primary">Delete Course</button>
        </form>
        @* <form method="post" asp-page-handler="ShowAddCourses">
            <div id="List" style="@Model.DisplayList">@Html.Raw(@Model.List)</div>
        </form> *@
    </div>
</div>
@* <div class="row">
    <div id="List" style="@Model.DisplayList">@Html.Raw(@Model.List)</div>
</div> *@
<div id="CourseTable" style="@Model.DisplayList">


    @if (Model.List != null && Model.List.Count > 0)
    {
        <table class='table table-bordered table-striped'>
            <tr>
                <th>ID</th>
                <th>Course Name</th>
                <th>Course Number</th>
                <th>Teacher </th>

            </tr>

            @foreach (Course course in Model.List)
            {
                <tr>
                    <td>@course.CId</td>
                    <td>@course.CourseName</td>
                    <td>@course.CourseNumber</td>
                    <td>@course.Name</td>
                </tr>
            }

        </table>
    }
</div>
<div class="button-container">
    <div class="row">
        @* Add Insert part *@
        <form method="post" asp-page-handler="InsertCourse">
            <div id="active_input" style="@Model.active_input">
                <input type="text" id="newCourseName" name="newCourseName" class="input_field" placeholder="Course Name" />
                <input type="text" id="newCourseNumber" name="newCourseNumber" class="input_field" placeholder="Course Number" />
                <input type="text" id="newCourseTeacher" name="newCourseTeacher" class="input_field" placeholder="Teacher" />

                <button type="submit" value="Insert" id="submitNewButton" style="@Model.insert_button">
                    Insert
                </button>
                <div style="color: red; font-size: 1.0em; position: absolute">
                    @Model.insertMSG
                </div>
            </div>
        </form>
    </div>
    @* Delete part *@
    <form method="post" asp-page-handler="DeleteCourse">
        <div id="delete_input" style="@Model.delete_input">
            <input type="text" id="deleteCourseName" class="input_field" placeholder="Course Name to Remove" />
            <input type="text" id="deleteCourseNumber" class="input_field" placeholder="Course Number to Remove" />
            <input type="text" id="deleteCourseTeacher" class="input_field" placeholder="Teacher to Remove" />
        </div>
        <div>
            <input type="button" value="Delete" id="deleteButton" style="@Model.deleteButton" />
            <div style="color: red; font-size: 1.0em; position: absolute">
                @Model.deleteMSG
            </div>
        </div>
    </form>
</div>

Tashpa11/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tashpa11/Pages/Index1.cshtml
@page
@model Tashpa11.Pages.Index1Model
@{
}

Tashpa11/Pages/LogUp.cshtml
@page
@model Tashpa11.Pages.LogUpModel
@{
}
<script src="~/js/LogUp.js"></script>
<div>
    <h1 style="margin-left:40%;">LogUp Form</h1>
</div>
<div class="row justify-content-center align-itms-center">
    <div class="col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card h-100">
            <div class="card-header"<h1>Login</h1>
                    <div class="card-body">
                        <form method="post">

                    <table id="names">
                        <tr>
                            <td>User First Name</td>
                            <td id="fName">
                                <input type="text" name="Name" onkeyup="checkName(this, 'fmsg')" />
                            </td>
                            <td id="fmsg" class="messages" runat="server"></td>
                        </tr>
                        <tr>
                            <td>Last Name</td>
                            <td id="lName">
                                <input type="text" name="FName" onkeyup="checkName(this, 'lmsg')" />
                            </td>
                            <td id="lmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>User Name</td>
                            <td id="uName">
                                <input type="text" name="UserName" onkeyup="checkName(this, 'umsg')" />
                            </td>
                            <td id="umsg" class="messages" runat="server" style="color: red"></td>
                        </tr>
                        <tr>
                            <td>Password</td>
                            <td id="pName">
                                <input type="password" name="Password" onkeyup="checkPass(this)" />
                            </td>
                            <td id="pmsg" class="messages"></td>
                        <tr>
                            <td>E-Mail</td>
                            <td id="email1">
                                <input type="email" id="email" name="email" onkeyup="checkEmail(this)" />
                            </td>
                            <td id="emsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Phone</td>
                            <td id="tel">
                                <input type="tel" name="phone" onkeyup="checkTel(this)" />
                            </td>
                            <td id="tmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Gender</td>
                            <td id="gender">
                                <input type="radio" name="gender" value="Male" id="Male">
                                <label for="male">Male</label><br>
                                <input type="radio" name="gender" value="Female" id="Female">
                                <label for="female">Female</label>
                            </td>
                            <td id="gmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Hobbies</td>
                            <td id="hName">
                                <input type="text" name="hobbies" onkeyup="checkHobbies(this)" />
                            </td>
                            <td id="hmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Birth Date</td>
                            <td>
                                <input type="date" id="dName" name="birth">
                            </td>
                            <td id="dmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Confirmation</td>
                            <td>
                                <label for="cName">please confirm that all above is correct</label>
                                <input id="cName" type="checkbox" name="confirmation" onclick="clearConfirm()" />
                            </td>
                            <td id="cmsg" class="messages"></td>

                        </tr>
                    </table>



        <input type="submit" name="submit" class="login" value="LogUp" onclick="return login1()" />
        <input type="reset" class="reset" value="RESET" onclick="reset2('login-msg','password-msg')" />

        <div class="mb-3 form-text text-danger " id="msgBox">
        @Model.msg
        </div>
        <div class="check">
            Check Something
        </div>

                        </form>
                    <div>
            </div>
        </div>

Tashpa11/Pages/Login.cshtml
@page
@model Tashpa11.Pages.LoginModel
@{
}
<script src="~/js/Login.js"></script>
<div>
    <h1 style="margin-left:40%;">LogIn Form</h1>
</div>
<div class="row justify-content-center align-itms-center">
    <div class="col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card h-100">
            <div class="card-header"<h1>Login</h1>
                    <div class="card-body">
                        <form method="post">

                         <label>Login    </label>
                        <input type="text" name="userName" id="userName" placeholder="Login" onkeyup="checkLogInValidity(this, 'login-msg')" />
                        <span id="login-msg"></span>
                        <br/><br/>
                        <label>Paswword</label>
                        <input type="password" name="password" id="password" placeholder="password" onkeyup="checkLogInValidity(this, 'password-msg')" />
                        <span id="password-msg"></span>
                        <br/> <br/>


                            <input type="submit" name="submit" class="login" value="LogIn" onclick="return login1()" />
                            <input type="reset" class="reset" value="RESET" onclick="reset2('login-msg','password-msg')" />

                            <div class="mb-3 form-text text-danger " id="msgBox">
                            @Model.msg
                            </div>
                            <div class="check">
                                Check Something
                            </div>

                        </form>
                    <div>
            </div>
        </div>

Tashpa11/Pages/Login/Exit.cshtml
@page
@model Tashpa11.Pages.Login.ExitModel
@{
}
<h1>exit</h1>

Tashpa11/Pages/Login/LogUp.cshtml
@page
@model LogUpModel
@{
}
<script src="~/js/LogUp.js"></script>
<div>
    <h1 style="margin-left:40%;">LogUp Form</h1>
</div>
<div class="row justify-content-center align-itms-center">
    <div class="col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card h-100">
            <div class="card-header"<h1>Login</h1>
                    <div class="card-body">
                        <form method="post">

                    <table id="names">
                        <tr>
                            <td>User First Name</td>
                            <td id="fName">
                                <input type="text" name="Name" onkeyup="checkName(this, 'fmsg')" />
                            </td>
                            <td id="fmsg" class="messages" runat="server"></td>
                        </tr>
                        <tr>
                            <td>Last Name</td>
                            <td id="lName">
                                <input type="text" name="FName" onkeyup="checkName(this, 'lmsg')" />
                            </td>
                            <td id="lmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>User Name</td>
                            <td id="uName">
                                <input type="text" name="UserName" onkeyup="checkName(this, 'umsg')" />
                            </td>
                            <td id="umsg" class="messages" runat="server" style="color: red"></td>
                        </tr>
                        <tr>
                            <td>Password</td>
                            <td id="pName">
                                <input type="password" name="Password" onkeyup="checkPass(this)" />
                            </td>
                            <td id="pmsg" class="messages"></td>
                        <tr>
                            <td>E-Mail</td>
                            <td id="email1">
                                <input type="email" id="email" name="email" onkeyup="checkEmail(this)" />
                            </td>
                            <td id="emsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Phone</td>
                            <td id="tel">
                                <input type="tel" name="phone" onkeyup="checkTel(this)" />
                            </td>
                            <td id="tmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Gender</td>
                            <td id="gender">
                                <input type="radio" name="gender" value="Male" id="Male">
                                <label for="male">Male</label><br>
                                <input type="radio" name="gender" value="Female" id="Female">
                                <label for="female">Female</label>
                            </td>
                            <td id="gmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Hobbies</td>
                            <td id="hName">
                                <input type="text" name="hobbies" onkeyup="checkHobbies(this)" />
                            </td>
                            <td id="hmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Birth Date</td>
                            <td>
                                <input type="date" id="dName" name="birth">
                            </td>
                            <td id="dmsg" class="messages"></td>
                        </tr>
                        <tr>
                            <td>Confirmation</td>
                            <td>
                                <label for="cName">please confirm that all above is correct</label>
                                <input id="cName" type="checkbox" name="confirmation" onclick="clearConfirm()" />
                            </td>
                            <td id="cmsg" class="messages"></td>

                        </tr>
                    </table>



        <input type="submit" name="submit" class="login" value="LogUp" onclick="return login1()" />
        <input type="reset" class="reset" value="RESET" onclick="reset2('login-msg','password-msg')" />

        <div class="mb-3 form-text text-danger " id="msgBox">
        @Model.msg
        </div>
        <div class="check">
            Check Something
        </div>

                        </form>
                    <div>
            </div>
        </div>

Tashpa11/Pages/Login/Login.cshtml
@page
@model LoginModel
@{
}
<script src="~/js/Login.js"></script>
<div>
    <h1 style="margin-left:40%;">LogIn Form</h1>
</div>
<div class="row justify-content-center align-itms-center">
    <div class="col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card h-100">
            <div class="card-header"<h1>Login</h1>
                    <div class="card-body">
                        <form method="post">

                         <label>Login    </label>
                        <input type="text" name="userName" id="userName" placeholder="Login" onkeyup="checkLogInValidity(this, 'login-msg')" />
                        <span id="login-msg"></span>
                        <br/><br/>
                        <label>Paswword</label>
                        <input type="password" name="password" id="password" placeholder="password" onkeyup="checkLogInValidity(this, 'password-msg')" />
                        <span id="password-msg"></span>
                        <br/> <br/>


                            <input type="submit" name="submit" class="login" value="LogIn" onclick="return login1()" />
                            <input type="reset" class="reset" value="RESET" onclick="reset2('login-msg','password-msg')" />

                            <div class="mb-3 form-text text-danger " id="msgBox">
                            @Model.msg
                            </div>
                            <div class="check">
                                Check Something
                            </div>

                        </form>
                    <div>
            </div>
        </div>

Tashpa11/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@{
    var sessionValue = Context.Session.GetString("Username");
    var sessionAdmin = Context.Session.GetString("Admin");
    var sessionFirst = Context.Session.GetString("Admin");

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tashpa11</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tashpa11.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Tashpa11</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                    <div class="dropdown d-inline-flex justify-content-around">
                        <a class="btn  dropdown-toggle text-dark " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Login</a>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link text-dark" href="~/Login/Login">Login</a></li>
                            <li><a class="nav-link text-dark" href="~/Login/LogUp">LogUp</a></li>
                            <li><a class="nav-link text-dark" href="~/Login/Exit">Exit</a></li>
                        </ul>
                    </div>
                    <div class="dropdown user-only">
                        <a class="btn  dropdown-toggle text-dark " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Students </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="~/Students/MangeMyCourses">Manage Students</a></li>
                        </ul>
                    </div>
                    <div class="dropdown user-admin">
                        <a class="btn  dropdown-toggle text-dark " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Courses</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="~/Courses/ManageCourses">Manage Courses</a></li>
                        </ul>
                    </div>
                    <ul>
                        <li class="nav-item">
                            <a class="btn nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    
        @if (!string.IsNullOrEmpty(sessionValue))
        {
            <script>
                const userOnlyElements = document.querySelectorAll(".user-only");
                userOnlyElements.forEach(element => {
                    element.style.display = 'block';
                });
            </script>
        }
        @if (string.IsNullOrEmpty(sessionValue))
        {
            <script>
                const userOnlyElements = document.querySelectorAll(".user-only");
                userOnlyElements.forEach(element => {
                    element.style.display = 'none';
                });
            </script>
        }
        @if (sessionAdmin == "Admin")
        {
            <script>
                const adminOnlyElements = document.querySelectorAll(".user-admin");
                adminOnlyElements.forEach(element => {
                    element.style.display = 'block';
                });
            </script>
        }
        @if (sessionAdmin != "Admin")
        {
            <script>
                const adminOnlyElements = document.querySelectorAll(".user-admin");
                adminOnlyElements.forEach(element => {
                    element.style.display = 'none';
                });
            </script>
        }
    

    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Tashpa11/Pages/Students/MangeMyCourses.cshtml
@page
@model Tashpa11.Pages.Students.MangeMyCoursesModel
@{
}
<div class="active_buttons">
    <form method="get" asp-page-handler="RenderCourses">
        <button type="submit" value="Show All Courses" class="btn btn-primary" >Show All Courses</button>
    </form>
    <form method="post" asp-page-handler="ShowAddCourses">
        <button type="submit" value="Add Course" class="btn btn-primary">Add Course</button>
    </form>
    <form method="post" asp-page-handler="ShowDeleteCourse">
        <button type="submit" value="Delete Course" class="btn btn-primary">Delete Course</button>
    </form>
</div>
<form method="post" asp-page-handler="ShowAddCourses">
    <div id="List" style="@Model.DisplayList">@Html.Raw(@Model.List)</div>
</form>

@* Add Insert part *@
<form method="post" asp-page-handler="InsertCourse">
    <div id="active_input" style="@Model.active_input">
        <input type="text" id="newCourseName" name="newCourseName" class="input_field" placeholder="Course Name" />
        <input type="text" id="newCourseNumber" name="newCourseNumber" class="input_field" placeholder="Course Number" />
        <input type="text" id="newCourseTeacher" name="newCourseTeacher" class="input_field" placeholder="Teacher" />

        <button type="submit" value="Insert" id="submitNewButton" style="@Model.insert_button">
            Insert
        </button>
        <div style="color: red; font-size: 1.0em; position: absolute">
            @Model.insertMSG
        </div>
    </div>
</form>

@* Delete part *@
<form method="post" asp-page-handler="DeleteCourse">
    <div id="delete_input" style="@Model.delete_input">
        <input type="text" id="deleteCourseName" class="input_field" placeholder="Course Name to Remove" />
        <input type="text" id="deleteCourseNumber" class="input_field" placeholder="Course Number to Remove" />
        <input type="text" id="deleteCourseTeacher" class="input_field" placeholder="Teacher to Remove" />
    </div>
    <div>
        <input type="button" value="Delete" id="deleteButton" style="@Model.deleteButton" />
        <div style="color: red; font-size: 1.0em; position: absolute">
            @Model.deleteMSG
    </div>
</form>